apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sre-demo-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/lschifferx/sre-pleno-teste.git
    targetRevision: development
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: sre-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
