---
apiVersion: v1
kind: Namespace
metadata:
  name: sre-demo
  labels:
    name: sre-demo

---
apiVersion: v1
kind: Service
metadata:
  name: sre-demo-app
  namespace: sre-demo
  labels:
    app: sre-demo-app
spec:
  type: ClusterIP
  selector:
    app: sre-demo-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
